#!/bin/bash

# Get the parent directory of where this script is.
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )/.." && pwd )"

# Change into that directory
cd "$DIR"

TAG=$(./bin/aliyundisk-provisioner -version | awk '{print $3}')
IMAGE=pragkent/aliyundisk-provisioner:$TAG

docker build -t $IMAGE .
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker push $IMAGE
